// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-pricing.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var plans = [
  { name: "1 Month", price: "$50", duration: "1 month", includes: ["System Access"] },
  { name: "3 Months", price: "$130", duration: "3 months", includes: ["System Access", "Self Learning Training Included"] },
  { name: "6 Months", price: "$250", duration: "6 months", includes: ["System Access", "Self Learning Training Included"] },
  { name: "1 Year", price: "$450", duration: "12 months", includes: ["System Access", "Self Learning Training Included"] },
  { name: "Dedicated Server", price: "From $499/month", duration: "monthly", includes: ["Dedicated SAP S/4HANA server"] }
];
var get_pricing_default = defineTool({
  name: "get_pricing",
  title: "Get pricing plans",
  description: "Get all Way2ERP SAP S/4HANA subscription plans and pricing.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(plans, null, 2) }],
    structuredContent: { plans }
  })
});

// src/lib/mcp/tools/get-features.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var features = [
  { title: "Enterprise S/4HANA", description: "Access real SAP S/4HANA 2025 systems with full Fiori UI experience." },
  { title: "Remote Access through RDP", description: "Multi-user remote access to the SAP environment via RDP." },
  { title: "Self Learning Training", description: "Included with 3-month, 6-month, and 1-year plans." }
];
var get_features_default = defineTool2({
  name: "get_features",
  title: "Get platform features",
  description: "List key features of the Way2ERP SAP S/4HANA training platform.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(features, null, 2) }],
    structuredContent: { features }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var contact = {
  website: "https://us.way2erp.com",
  paypal: "https://paypal.me/mascorpit",
  paypalEmail: "mascorpit@gmail.com",
  demoRequestUrl: "https://us.way2erp.com/#contact"
};
var get_contact_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact & payment info",
  description: "Get Way2ERP contact details, demo request URL, and PayPal payment link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "way2erp-mcp",
  title: "Way2ERP MCP",
  version: "0.1.0",
  instructions: "Public MCP server for Way2ERP, an SAP S/4HANA training platform. Use these tools to look up pricing plans, platform features, and contact/payment info.",
  tools: [get_pricing_default, get_features_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
